-- MySQL Script generated by MySQL Workbench
-- Tue Mar  6 17:23:46 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `magiclink` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `magiclink` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `magiclink` ;

-- -----------------------------------------------------
-- Table `Nivel_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Nivel_usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Nivel_usuario` (
  `id_nivel_usuario` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_nivel_usuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pessoa` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Pessoa` (
  `id_pessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `nome_fantasia` VARCHAR(100) NULL,
  `data_nascimento` DATE NULL,
  `sexo` CHAR(2) NULL,
  `cpf_cnjp` VARCHAR(80) NOT NULL,
  `email` VARCHAR(100) NULL,
  `inscricao_estadual` VARCHAR(100) NULL,
  `inscricao_municipal` VARCHAR(100) NULL,
  `flg_pessoa_juridica` TINYINT NULL,
  `senha` VARCHAR(80) NULL,
  `id_nivel_usuario` INT NOT NULL,
  `img_user` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Endereco` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Endereco` (
  `id_pessoa` INT NOT NULL,
  `endereco` VARCHAR(200) NULL,
  `rua` VARCHAR(50) NULL,
  `bairro` VARCHAR(30) NULL,
  `numero` INT NULL,
  `cidade_id` INT NULL,
  `cep` VARCHAR(30) NULL,
  `Endereçocol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Telefone` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Telefone` (
  `id_pessoa` INT NOT NULL,
  `celular` VARCHAR(30) NULL,
  `fixo` VARCHAR(30) NULL,
  PRIMARY KEY (`id_pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
